const NO_VALID = 400; // bad_request
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NO_FOUND = 404;
const CONFLICT = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  NO_VALID,
  UNAUTHORIZED,
  FORBIDDEN,
  NO_FOUND,
  CONFLICT,
  INTERNAL_SERVER_ERROR,
};
